# Generated by Django 5.1.3 on 2024-11-30 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cato_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('fprice', models.IntegerField()),
                ('fsellprice', models.IntegerField()),
                ('fdiscount', models.IntegerField()),
                ('fimage', models.ImageField(blank=True, default='', upload_to='fruit')),
                ('fdescription', models.TextField()),
                ('menus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superadmin.menus')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=255)),
                ('pprice', models.IntegerField()),
                ('psellprice', models.IntegerField()),
                ('pdiscount', models.IntegerField()),
                ('pimage', models.ImageField(blank=True, default='', upload_to='product')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='superadmin.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amt', models.IntegerField()),
                ('status', models.BooleanField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.customer')),
                ('fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superadmin.fruit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.product')),
            ],
        ),
    ]
