# Generated by Django 5.1.3 on 2024-12-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
