# Generated by Django 5.1.3 on 2024-12-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_cart_is_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='fimage',
            field=models.ImageField(blank=True, default='', upload_to='product'),
        ),
    ]
