# Generated by Django 5.1.3 on 2024-12-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
