# Generated by Django 5.1.3 on 2024-11-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, default='', upload_to='profile')),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
