# Generated by Django 5.1.3 on 2025-04-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
